### ISSUE TITLE
Drastic menu shown by click R3

### ISSUE THREAD

**Issue by ridhoperdana** [Vidnez/Drastic-Patch-for-RGB30-20sx#1]
Hi, thank you for the patch. It is working flawlessly.

But i have question, after I install the patch my button to show drastic option is by clicking R3 instead of L3. This made the virtual touchscreen tap clickable with L3.

How to revert it like the default arkOS?

Thanks!

**Comment by Vidnez** [comment]
Hi,

Unzip this file and replace  ./opt/drastic/config/drastic.cfg 

[drastic.cfg.zip](https://github.com/user-attachments/files/17775260/drastic.cfg.zip)
